package.json
src/linagora.esn.contact/images/contacts-icon.svg
webpack.commons.js

 #15 add favicon

---

assets/index.pug
src/app/app-loading.pug
src/app/app.run.js

Closes #17
Please see here https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/23 for video screenshots

 #17 Add a splashscreen

---

.env.example
.gitignore
README.md
package.json
webpack.commons.js

Partially resolves https://github.com/OpenPaaS-Suite/esn/issues/24.

https://github.com/OpenPaaS-Suite/esn/issues/24: Brought the new application grid to the Contacts SPA

---

src/linagora.esn.contact/app/contact/contact.service.js

 56 Use location to set OpenPaaS server URL

---

src/app/app.js
src/linagora.esn.contact.collect/app/addressbook/contact-collect-addressbook-display-shell.service.js
src/linagora.esn.contact.collect/app/addressbook/contact-collect-addressbook.service.js
src/linagora.esn.contact.collect/app/addressbook/contact-collect-addressbook.service.spec.js
src/linagora.esn.contact.collect/app/app.module.js
src/linagora.esn.contact.collect/app/app.run.js
src/module-info.json

Resolves https://github.com/OpenPaaS-Suite/esn-frontend-contacts/issues/51

OpenPaaS-Suite/esn-frontend-contacts#51 - Bring Back Module linagora.esn.contact.collect

---

src/linagora.esn.contact/app/app.module.js
src/linagora.esn.contact/app/contact/contact.service.js

Partially resolves https://github.com/OpenPaaS-Suite/esn-dav-import-client/issues/5. Please also refer to https://github.com/OpenPaaS-Suite/esn-dav-import-client/pull/6.

esn-dav-import-client#5: Adjusted the way ESNDavImportClient is constructed to allow passing only a single instance of Client

---

src/linagora.esn.contact/app/app.pug

closes https://github.com/OpenPaaS-Suite/esn/issues/35

OpenPaaS-Suite/esn#35 fix no animation

---

src/linagora.esn.contact/app/app.module.js
src/linagora.esn.contact/app/app.run.js
src/linagora.esn.contact/app/contact/form/contact-edition-form.pug

#46 allow to edit contact profile

---

.env.example
package.json
webpack.commons.js

related to OpenPaaS-Suite/openpaas-auth-client#5

OpenPaaS-Suite/openpaas-auth-client#5 Support OIDC silent renew

---

src/linagora.esn.contact/i18n/fr.json

closes https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/327

#327 fixed an invalid French translation

---

webpack.commons.js

partially resolves https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/453

calendar#453 added env/openpaas.js file and excluded it from the webpack bundle

---

src/linagora.esn.contact/app/app.module.js

DEMO:
https://user-images.githubusercontent.com/43316837/111510473-1ab1f080-874e-11eb-8a8a-127e853be59b.mp4

#96 missing module for open paas spinner

---

src/esn.contact.libs/app/addressBook/addressbook-display.service.js
src/linagora.esn.contact/app/addressbook/settings/contact-addressbook-settings.pug
src/linagora.esn.contact/app/addressbook/settings/main/contact-addressbook-settings-main.pug

https://user-images.githubusercontent.com/6764881/111460815-b4f94080-871c-11eb-8c82-cc2ae8b5a3db.mp4

#98 fixed the sharing address book feature flag not being respected

---

src/linagora.esn.contact/app/app.routes.js

#102: Added the address book configuration dialog route state

---

src/linagora.esn.contact/app/app.controllers.js
src/linagora.esn.contact/app/app.module.js
src/linagora.esn.contact/app/app.routes.js
src/linagora.esn.contact/app/contact/edit/contact-edit.component.js

Resolves #110. This PR is quite similar to #116.

#110: Added edit contact dialog route state

---

src/linagora.esn.contact/app/app.module.js
src/linagora.esn.contact/app/app.routes.js
src/linagora.esn.contact/app/contact/show/contact-show.component.js
src/linagora.esn.contact/app/controllers/contact-show.controller.js

Resolves #105.
demo using a dummy template
https://user-images.githubusercontent.com/6764881/111955573-f6f20000-8ae9-11eb-9180-47244db39d4e.mp4

#105 contact display dialog route state

---

src/linagora.esn.contact/app/app.routes.js

**DEMO :**
https://user-images.githubusercontent.com/43316837/111963106-6fa98a00-8af3-11eb-829c-1e98d2c573fe.mp4

#108 adapt existing state of new contact to add modal

---

src/linagora.esn.contact/app/app.module.js
src/linagora.esn.contact/app/contact/action/delete/contact-delete-confirmation-dialog.pug
src/linagora.esn.contact/app/contact/show/contact-show.less
src/linagora.esn.contact/app/contact/show/contact-show.pug
src/linagora.esn.contact/app/controllers/contact-show.controller.js
src/linagora.esn.contact/app/controllers/contact-show.controller.spec.js
src/linagora.esn.contact/app/services/contact-delete-confirmation-dialog.service.js
src/linagora.esn.contact/i18n/en.json
src/linagora.esn.contact/i18n/fr.json
src/linagora.esn.contact/i18n/ru.json
src/linagora.esn.contact/i18n/vi.json
src/linagora.esn.contact/i18n/zh.json

https://user-images.githubusercontent.com/6764881/112021977-2167ab80-8b32-11eb-9da6-5a1733dd3789.mp4
https://user-images.githubusercontent.com/6764881/112021998-275d8c80-8b32-11eb-8008-53ef59106652.mp4
https://user-images.githubusercontent.com/6764881/112188763-90f99b80-8c03-11eb-8a5c-67cf89ba063a.mp4
https://user-images.githubusercontent.com/6764881/112197175-15501c80-8c0c-11eb-9997-51513faf5925.mp4

#106 create a new display dialog template

---

src/linagora.esn.contact/app/addressbook/settings/contact-addressbook-settings.controller.spec.js
src/linagora.esn.contact/app/app.less
src/linagora.esn.contact/app/app.run.js
src/linagora.esn.contact/app/contact/action/copy/contact-action-copy-dialog.pug
src/linagora.esn.contact/app/contact/action/copy/contact-action-copy.pug
src/linagora.esn.contact/app/contact/action/delete/contact-delete-action-item.pug
src/linagora.esn.contact/app/contact/action/edit/contact-edit-action-item.pug
src/linagora.esn.contact/app/contact/action/move/contact-action-move-dialog.pug
src/linagora.esn.contact/app/contact/action/move/contact-action-move.pug
src/linagora.esn.contact/app/contact/contact.less
src/linagora.esn.contact/app/contact/show/contact-show.less
src/linagora.esn.contact/app/contact/show/contact-show.pug
src/linagora.esn.contact/i18n/en.json
src/linagora.esn.contact/i18n/fr.json
src/linagora.esn.contact/i18n/ru.json
src/linagora.esn.contact/i18n/vi.json
src/linagora.esn.contact/i18n/zh.json

#106: Fixed some minor UI in the contact display dialog

---

src/linagora.esn.contact/app/contact/contact.less
src/linagora.esn.contact/app/contact/create/contact-create.pug
src/linagora.esn.contact/app/contact/form/contact-edition-form.directive.js
src/linagora.esn.contact/app/contact/form/contact-edition-form.pug
src/linagora.esn.contact/app/contact/form/contact-edition-modal.less

Demo
https://user-images.githubusercontent.com/43316837/112539999-f7bcb780-8db1-11eb-9ae8-581e5ad8598b.mp4

#107 update new contact dialog

---

src/linagora.esn.contact/app/contact/list/contact-list-card.pug
src/linagora.esn.contact/app/contact/list/contact-list-item.pug
src/linagora.esn.contact/css/styles.less

#125: Improved the contact card display

---

src/linagora.esn.contact/app/controllers/contact-list.controller.js
src/linagora.esn.contact/app/controllers/contact-show.controller.js
src/linagora.esn.contact/app/controllers/contact-show.controller.spec.js
src/linagora.esn.contact/app/services/live-update/contact-live-update.service.js
src/linagora.esn.contact/app/services/live-update/contact-live-update.service.spec.js

https://user-images.githubusercontent.com/6764881/112902730-7715f800-90de-11eb-953d-9aec4fb23b8b.mp4

#129 fixed redirection failing after move to/delete actions

---

src/linagora.esn.contact/app/contact/form/contact-edition-form.pug
src/linagora.esn.contact/app/contact/form/contact-edition-modal.less
src/linagora.esn.contact/app/contact/photo/contact-photo-child.pug

https://user-images.githubusercontent.com/43316837/113159500-8e66f980-9234-11eb-821e-e5d4e5c08721.mp4

#490 update profile picture

---

src/linagora.esn.contact/app/app.controllers.js
src/linagora.esn.contact/app/app.controllers.spec.js
src/linagora.esn.contact/app/app.routes.js
src/linagora.esn.contact/app/contact/create/contact-create.pug
src/linagora.esn.contact/app/contact/edit/contact-edit.pug
src/linagora.esn.contact/app/contact/form/contact-edition-form.directive.js
src/linagora.esn.contact/app/contact/form/contact-edition-form.pug
src/linagora.esn.contact/app/contact/photo/contact-photo-child.pug

https://user-images.githubusercontent.com/43316837/113157301-adfd2280-9232-11eb-9a45-22bcef65180d.mp4

#109 update edit contact with new design 

---

src/linagora.esn.contact/app/app.controllers.js
src/linagora.esn.contact/app/app.controllers.spec.js
src/linagora.esn.contact/app/app.module.js
src/linagora.esn.contact/app/app.routes.js
src/linagora.esn.contact/app/contact/create/contact-create.pug
src/linagora.esn.contact/app/contact/edit/contact-edit.component.js
src/linagora.esn.contact/app/contact/edit/contact-edit.pug
src/linagora.esn.contact/app/contact/form/contact-edition-form.directive.js
src/linagora.esn.contact/app/contact/form/contact-edition-form.directive.spec.js
src/linagora.esn.contact/app/contact/form/contact-edition-form.pug
src/linagora.esn.contact/app/contact/form/contact-edition-modal.less

#130: Fix the close button of the create contact dialog

---

src/linagora.esn.contact/app/contact/form/contact-edition-modal.less

#141: The contact edition dialog is now scrollable when the content is too long

---

src/linagora.esn.contact/app/contact/form/contact-edition-form.directive.js
src/linagora.esn.contact/app/contact/form/contact-edition-form.directive.spec.js
src/linagora.esn.contact/app/contact/form/contact-edition-form.pug
src/linagora.esn.contact/app/contact/form/contact-edition-modal.less

https://user-images.githubusercontent.com/6764881/113609167-53553380-9643-11eb-9644-72bacda25601.mp4

#101 display the shared addressbook owner in the selection when creating a new contact

---

package.json
webpack.prod.js

Module ngx_http_gzip_static_module already added here https://github.com/linagora/esn-frontend-contacts/commit/8965e2315f84808def48b75997b376715b2b4575

customers#45 Enable gzip compression

---

src/linagora.esn.contact/app/addressbook/addressbook-shared-configuration/addressbook-shared-configuration.pug
src/linagora.esn.contact/app/app.run.js

#174: Add shared dialog template in cache

---

LICENSE

As per Linagora board of director decision

Adopt AGPL V3
